// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_spca_RCPPEXPORTS_H_GEN_
#define RCPP_spca_RCPPEXPORTS_H_GEN_

#include <RcppEigen.h>
#include <Rcpp.h>

namespace spca {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("spca", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("spca", "_spca_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in spca");
            }
        }
    }

    inline Eigen::VectorXd vifXC(Eigen::Map<Eigen::MatrixXd> X, Eigen::VectorXi ind, bool intercept = false) {
        typedef SEXP(*Ptr_vifXC)(SEXP,SEXP,SEXP);
        static Ptr_vifXC p_vifXC = NULL;
        if (p_vifXC == NULL) {
            validateSignature("Eigen::VectorXd(*vifXC)(Eigen::Map<Eigen::MatrixXd>,Eigen::VectorXi,bool)");
            p_vifXC = (Ptr_vifXC)R_GetCCallable("spca", "_spca_vifXC");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_vifXC(Shield<SEXP>(Rcpp::wrap(X)), Shield<SEXP>(Rcpp::wrap(ind)), Shield<SEXP>(Rcpp::wrap(intercept)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Eigen::VectorXd >(rcpp_result_gen);
    }

    inline Eigen::VectorXd vifSC(Eigen::Map<Eigen::MatrixXd> S, Eigen::VectorXi ind) {
        typedef SEXP(*Ptr_vifSC)(SEXP,SEXP);
        static Ptr_vifSC p_vifSC = NULL;
        if (p_vifSC == NULL) {
            validateSignature("Eigen::VectorXd(*vifSC)(Eigen::Map<Eigen::MatrixXd>,Eigen::VectorXi)");
            p_vifSC = (Ptr_vifSC)R_GetCCallable("spca", "_spca_vifSC");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_vifSC(Shield<SEXP>(Rcpp::wrap(S)), Shield<SEXP>(Rcpp::wrap(ind)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Eigen::VectorXd >(rcpp_result_gen);
    }

    inline Eigen::VectorXd vifSPseudoC(Eigen::Map<Eigen::MatrixXd> S, Eigen::VectorXi ind) {
        typedef SEXP(*Ptr_vifSPseudoC)(SEXP,SEXP);
        static Ptr_vifSPseudoC p_vifSPseudoC = NULL;
        if (p_vifSPseudoC == NULL) {
            validateSignature("Eigen::VectorXd(*vifSPseudoC)(Eigen::Map<Eigen::MatrixXd>,Eigen::VectorXi)");
            p_vifSPseudoC = (Ptr_vifSPseudoC)R_GetCCallable("spca", "_spca_vifSPseudoC");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_vifSPseudoC(Shield<SEXP>(Rcpp::wrap(S)), Shield<SEXP>(Rcpp::wrap(ind)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Eigen::VectorXd >(rcpp_result_gen);
    }

}

#endif // RCPP_spca_RCPPEXPORTS_H_GEN_
