// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// aatC
Eigen::MatrixXd aatC(const Eigen::Map<Eigen::MatrixXd>& A);
RcppExport SEXP _spca_aatC(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(aatC(A));
    return rcpp_result_gen;
END_RCPP
}
// ataC
Eigen::MatrixXd ataC(const Eigen::Map<Eigen::MatrixXd>& A);
RcppExport SEXP _spca_ataC(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(ataC(A));
    return rcpp_result_gen;
END_RCPP
}
// atbC
Eigen::MatrixXd atbC(const Eigen::Map<Eigen::MatrixXd>& A, const Eigen::Map<Eigen::MatrixXd>& B);
RcppExport SEXP _spca_atbC(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(atbC(A, B));
    return rcpp_result_gen;
END_RCPP
}
// abC
Eigen::MatrixXd abC(const Eigen::Map<Eigen::MatrixXd>& A, const Eigen::Map<Eigen::MatrixXd>& B);
RcppExport SEXP _spca_abC(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(abC(A, B));
    return rcpp_result_gen;
END_RCPP
}
// abtC
Eigen::MatrixXd abtC(const Eigen::Map<Eigen::MatrixXd>& A, const Eigen::Map<Eigen::MatrixXd>& B);
RcppExport SEXP _spca_abtC(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(abtC(A, B));
    return rcpp_result_gen;
END_RCPP
}
// atdaC
Eigen::MatrixXd atdaC(const Eigen::Map<Eigen::MatrixXd>& A, const Eigen::Map<Eigen::MatrixXd>& D);
RcppExport SEXP _spca_atdaC(SEXP ASEXP, SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(atdaC(A, D));
    return rcpp_result_gen;
END_RCPP
}
// atdbC
Eigen::MatrixXd atdbC(const Eigen::Map<Eigen::MatrixXd>& A, const Eigen::Map<Eigen::MatrixXd>& D, const Eigen::Map<Eigen::MatrixXd>& B);
RcppExport SEXP _spca_atdbC(SEXP ASEXP, SEXP DSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(atdbC(A, D, B));
    return rcpp_result_gen;
END_RCPP
}
// avC
Eigen::VectorXd avC(const Eigen::Map<Eigen::MatrixXd>& A, const Eigen::Map<Eigen::VectorXd>& v);
RcppExport SEXP _spca_avC(SEXP ASEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(avC(A, v));
    return rcpp_result_gen;
END_RCPP
}
// atvC
Eigen::VectorXd atvC(const Eigen::Map<Eigen::MatrixXd>& A, const Eigen::Map<Eigen::VectorXd>& v);
RcppExport SEXP _spca_atvC(SEXP ASEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(atvC(A, v));
    return rcpp_result_gen;
END_RCPP
}
// vtaC
Eigen::VectorXd vtaC(const Eigen::Map<Eigen::VectorXd>& v, const Eigen::Map<Eigen::MatrixXd>& A);
RcppExport SEXP _spca_vtaC(SEXP vSEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(vtaC(v, A));
    return rcpp_result_gen;
END_RCPP
}
// vtauC
double vtauC(const Eigen::Map<Eigen::VectorXd>& v, const Eigen::Map<Eigen::MatrixXd>& A, const Eigen::Map<Eigen::VectorXd>& u);
RcppExport SEXP _spca_vtauC(SEXP vSEXP, SEXP ASEXP, SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type u(uSEXP);
    rcpp_result_gen = Rcpp::wrap(vtauC(v, A, u));
    return rcpp_result_gen;
END_RCPP
}
// vtvC
double vtvC(const Eigen::Map<Eigen::VectorXd>& v);
RcppExport SEXP _spca_vtvC(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(vtvC(v));
    return rcpp_result_gen;
END_RCPP
}
// vtuC
double vtuC(const Eigen::Map<Eigen::VectorXd>& v, const Eigen::Map<Eigen::VectorXd>& u);
RcppExport SEXP _spca_vtuC(SEXP vSEXP, SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type u(uSEXP);
    rcpp_result_gen = Rcpp::wrap(vtuC(v, u));
    return rcpp_result_gen;
END_RCPP
}
// traceC
double traceC(const Eigen::Map<Eigen::MatrixXd>& S);
RcppExport SEXP _spca_traceC(SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(traceC(S));
    return rcpp_result_gen;
END_RCPP
}
// EigenC
Rcpp::List EigenC(const Eigen::Map<Eigen::MatrixXd>& S);
RcppExport SEXP _spca_EigenC(SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(EigenC(S));
    return rcpp_result_gen;
END_RCPP
}
// compute_eigenvaluesC
Eigen::VectorXd compute_eigenvaluesC(const Eigen::Map<Eigen::MatrixXd>& S);
RcppExport SEXP _spca_compute_eigenvaluesC(SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_eigenvaluesC(S));
    return rcpp_result_gen;
END_RCPP
}
// GenEigenC
Rcpp::List GenEigenC(const Eigen::Map<Eigen::MatrixXd>& A, const Eigen::Map<Eigen::MatrixXd>& B);
RcppExport SEXP _spca_GenEigenC(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(GenEigenC(A, B));
    return rcpp_result_gen;
END_RCPP
}
// solveC
Eigen::MatrixXd solveC(const Eigen::Map<Eigen::MatrixXd>& S);
RcppExport SEXP _spca_solveC(SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(solveC(S));
    return rcpp_result_gen;
END_RCPP
}
// scaleC
Eigen::MatrixXd scaleC(const Eigen::Map<Eigen::MatrixXd>& A, bool center, bool scale);
RcppExport SEXP _spca_scaleC(SEXP ASEXP, SEXP centerSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type A(ASEXP);
    Rcpp::traits::input_parameter< bool >::type center(centerSEXP);
    Rcpp::traits::input_parameter< bool >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(scaleC(A, center, scale));
    return rcpp_result_gen;
END_RCPP
}
// scaleColsC
Eigen::MatrixXd scaleColsC(const Eigen::Map<Eigen::MatrixXd>& A, int normtype, const Eigen::Map<Eigen::VectorXd>& sig);
RcppExport SEXP _spca_scaleColsC(SEXP ASEXP, SEXP normtypeSEXP, SEXP sigSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type normtype(normtypeSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd>& >::type sig(sigSEXP);
    rcpp_result_gen = Rcpp::wrap(scaleColsC(A, normtype, sig));
    return rcpp_result_gen;
END_RCPP
}
// make_vexpSC
List make_vexpSC(const Eigen::Map<Eigen::MatrixXd>& A, const Eigen::Map<Eigen::MatrixXd>& S);
RcppExport SEXP _spca_make_vexpSC(SEXP ASEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(make_vexpSC(A, S));
    return rcpp_result_gen;
END_RCPP
}
// var2corC
Eigen::MatrixXd var2corC(Eigen::Map<Eigen::MatrixXd > S);
RcppExport SEXP _spca_var2corC(SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd > >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(var2corC(S));
    return rcpp_result_gen;
END_RCPP
}
// makeCorCompC
Eigen::MatrixXd makeCorCompC(const Eigen::Map<Eigen::MatrixXd>& A, const Eigen::Map<Eigen::MatrixXd>& S, int d);
RcppExport SEXP _spca_makeCorCompC(SEXP ASEXP, SEXP SSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type S(SSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(makeCorCompC(A, S, d));
    return rcpp_result_gen;
END_RCPP
}
// makeCorScoresC
Eigen::MatrixXd makeCorScoresC(const Eigen::Map<Eigen::MatrixXd>& T, int d);
RcppExport SEXP _spca_makeCorScoresC(SEXP TSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(makeCorScoresC(T, d));
    return rcpp_result_gen;
END_RCPP
}
// PMAllEigen
Rcpp::List PMAllEigen(const Eigen::Map<Eigen::MatrixXd>& M, int ncomps, bool fat_matrix, double epsPM, int maxiterPM);
RcppExport SEXP _spca_PMAllEigen(SEXP MSEXP, SEXP ncompsSEXP, SEXP fat_matrixSEXP, SEXP epsPMSEXP, SEXP maxiterPMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type ncomps(ncompsSEXP);
    Rcpp::traits::input_parameter< bool >::type fat_matrix(fat_matrixSEXP);
    Rcpp::traits::input_parameter< double >::type epsPM(epsPMSEXP);
    Rcpp::traits::input_parameter< int >::type maxiterPM(maxiterPMSEXP);
    rcpp_result_gen = Rcpp::wrap(PMAllEigen(M, ncomps, fat_matrix, epsPM, maxiterPM));
    return rcpp_result_gen;
END_RCPP
}
// pcaC
Rcpp::List pcaC(const Eigen::Map<Eigen::MatrixXd>& M, int ncomps, bool data_matrix, bool fat_matrix, bool PM, double epsPM, int maxiterPM);
RcppExport SEXP _spca_pcaC(SEXP MSEXP, SEXP ncompsSEXP, SEXP data_matrixSEXP, SEXP fat_matrixSEXP, SEXP PMSEXP, SEXP epsPMSEXP, SEXP maxiterPMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type ncomps(ncompsSEXP);
    Rcpp::traits::input_parameter< bool >::type data_matrix(data_matrixSEXP);
    Rcpp::traits::input_parameter< bool >::type fat_matrix(fat_matrixSEXP);
    Rcpp::traits::input_parameter< bool >::type PM(PMSEXP);
    Rcpp::traits::input_parameter< double >::type epsPM(epsPMSEXP);
    Rcpp::traits::input_parameter< int >::type maxiterPM(maxiterPMSEXP);
    rcpp_result_gen = Rcpp::wrap(pcaC(M, ncomps, data_matrix, fat_matrix, PM, epsPM, maxiterPM));
    return rcpp_result_gen;
END_RCPP
}
// lsspcaTC
List lsspcaTC(const Eigen::Map<Eigen::MatrixXd>& X, int ncomps, int stop_criterion, bool exact_cvexp, double alpha, double ncompbycvexp, Rcpp::CharacterVector method, Rcpp::Nullable<Rcpp::IntegerVector> indvec_in, Rcpp::Nullable<Rcpp::IntegerVector> cardvec_in, bool PMPC, bool PMS, double epsPMPC, double epsPMS, int maxiterPMPC, int maxiterPMS, double rank_tol);
RcppExport SEXP _spca_lsspcaTC(SEXP XSEXP, SEXP ncompsSEXP, SEXP stop_criterionSEXP, SEXP exact_cvexpSEXP, SEXP alphaSEXP, SEXP ncompbycvexpSEXP, SEXP methodSEXP, SEXP indvec_inSEXP, SEXP cardvec_inSEXP, SEXP PMPCSEXP, SEXP PMSSEXP, SEXP epsPMPCSEXP, SEXP epsPMSSEXP, SEXP maxiterPMPCSEXP, SEXP maxiterPMSSEXP, SEXP rank_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type ncomps(ncompsSEXP);
    Rcpp::traits::input_parameter< int >::type stop_criterion(stop_criterionSEXP);
    Rcpp::traits::input_parameter< bool >::type exact_cvexp(exact_cvexpSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type ncompbycvexp(ncompbycvexpSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type method(methodSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type indvec_in(indvec_inSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type cardvec_in(cardvec_inSEXP);
    Rcpp::traits::input_parameter< bool >::type PMPC(PMPCSEXP);
    Rcpp::traits::input_parameter< bool >::type PMS(PMSSEXP);
    Rcpp::traits::input_parameter< double >::type epsPMPC(epsPMPCSEXP);
    Rcpp::traits::input_parameter< double >::type epsPMS(epsPMSSEXP);
    Rcpp::traits::input_parameter< int >::type maxiterPMPC(maxiterPMPCSEXP);
    Rcpp::traits::input_parameter< int >::type maxiterPMS(maxiterPMSSEXP);
    Rcpp::traits::input_parameter< double >::type rank_tol(rank_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(lsspcaTC(X, ncomps, stop_criterion, exact_cvexp, alpha, ncompbycvexp, method, indvec_in, cardvec_in, PMPC, PMS, epsPMPC, epsPMS, maxiterPMPC, maxiterPMS, rank_tol));
    return rcpp_result_gen;
END_RCPP
}
// lsspcaC
List lsspcaC(const Eigen::Map<Eigen::MatrixXd>& S, int ncomps, int selection_method, int stop_criterion, bool exact_cvexp, double alpha, double ncompbycvexp, Rcpp::CharacterVector method, Rcpp::Nullable<Rcpp::IntegerVector> indvec_in, Rcpp::Nullable<Rcpp::IntegerVector> cardvec_in, bool PMPC, bool PMS, double epsPMPC, double epsPMS, int maxiterPMPC, int maxiterPMS, double rank_tol);
RcppExport SEXP _spca_lsspcaC(SEXP SSEXP, SEXP ncompsSEXP, SEXP selection_methodSEXP, SEXP stop_criterionSEXP, SEXP exact_cvexpSEXP, SEXP alphaSEXP, SEXP ncompbycvexpSEXP, SEXP methodSEXP, SEXP indvec_inSEXP, SEXP cardvec_inSEXP, SEXP PMPCSEXP, SEXP PMSSEXP, SEXP epsPMPCSEXP, SEXP epsPMSSEXP, SEXP maxiterPMPCSEXP, SEXP maxiterPMSSEXP, SEXP rank_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type S(SSEXP);
    Rcpp::traits::input_parameter< int >::type ncomps(ncompsSEXP);
    Rcpp::traits::input_parameter< int >::type selection_method(selection_methodSEXP);
    Rcpp::traits::input_parameter< int >::type stop_criterion(stop_criterionSEXP);
    Rcpp::traits::input_parameter< bool >::type exact_cvexp(exact_cvexpSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type ncompbycvexp(ncompbycvexpSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type method(methodSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type indvec_in(indvec_inSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type cardvec_in(cardvec_inSEXP);
    Rcpp::traits::input_parameter< bool >::type PMPC(PMPCSEXP);
    Rcpp::traits::input_parameter< bool >::type PMS(PMSSEXP);
    Rcpp::traits::input_parameter< double >::type epsPMPC(epsPMPCSEXP);
    Rcpp::traits::input_parameter< double >::type epsPMS(epsPMSSEXP);
    Rcpp::traits::input_parameter< int >::type maxiterPMPC(maxiterPMPCSEXP);
    Rcpp::traits::input_parameter< int >::type maxiterPMS(maxiterPMSSEXP);
    Rcpp::traits::input_parameter< double >::type rank_tol(rank_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(lsspcaC(S, ncomps, selection_method, stop_criterion, exact_cvexp, alpha, ncompbycvexp, method, indvec_in, cardvec_in, PMPC, PMS, epsPMPC, epsPMS, maxiterPMPC, maxiterPMS, rank_tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spca_aatC", (DL_FUNC) &_spca_aatC, 1},
    {"_spca_ataC", (DL_FUNC) &_spca_ataC, 1},
    {"_spca_atbC", (DL_FUNC) &_spca_atbC, 2},
    {"_spca_abC", (DL_FUNC) &_spca_abC, 2},
    {"_spca_abtC", (DL_FUNC) &_spca_abtC, 2},
    {"_spca_atdaC", (DL_FUNC) &_spca_atdaC, 2},
    {"_spca_atdbC", (DL_FUNC) &_spca_atdbC, 3},
    {"_spca_avC", (DL_FUNC) &_spca_avC, 2},
    {"_spca_atvC", (DL_FUNC) &_spca_atvC, 2},
    {"_spca_vtaC", (DL_FUNC) &_spca_vtaC, 2},
    {"_spca_vtauC", (DL_FUNC) &_spca_vtauC, 3},
    {"_spca_vtvC", (DL_FUNC) &_spca_vtvC, 1},
    {"_spca_vtuC", (DL_FUNC) &_spca_vtuC, 2},
    {"_spca_traceC", (DL_FUNC) &_spca_traceC, 1},
    {"_spca_EigenC", (DL_FUNC) &_spca_EigenC, 1},
    {"_spca_compute_eigenvaluesC", (DL_FUNC) &_spca_compute_eigenvaluesC, 1},
    {"_spca_GenEigenC", (DL_FUNC) &_spca_GenEigenC, 2},
    {"_spca_solveC", (DL_FUNC) &_spca_solveC, 1},
    {"_spca_scaleC", (DL_FUNC) &_spca_scaleC, 3},
    {"_spca_scaleColsC", (DL_FUNC) &_spca_scaleColsC, 3},
    {"_spca_make_vexpSC", (DL_FUNC) &_spca_make_vexpSC, 2},
    {"_spca_var2corC", (DL_FUNC) &_spca_var2corC, 1},
    {"_spca_makeCorCompC", (DL_FUNC) &_spca_makeCorCompC, 3},
    {"_spca_makeCorScoresC", (DL_FUNC) &_spca_makeCorScoresC, 2},
    {"_spca_PMAllEigen", (DL_FUNC) &_spca_PMAllEigen, 5},
    {"_spca_pcaC", (DL_FUNC) &_spca_pcaC, 7},
    {"_spca_lsspcaTC", (DL_FUNC) &_spca_lsspcaTC, 16},
    {"_spca_lsspcaC", (DL_FUNC) &_spca_lsspcaC, 17},
    {NULL, NULL, 0}
};

RcppExport void R_init_spca(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
