# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aatC <- function(A) {
    .Call(`_spca_aatC`, A)
}

ataC <- function(A) {
    .Call(`_spca_ataC`, A)
}

atbC <- function(A, B) {
    .Call(`_spca_atbC`, A, B)
}

abC <- function(A, B) {
    .Call(`_spca_abC`, A, B)
}

abtC <- function(A, B) {
    .Call(`_spca_abtC`, A, B)
}

atdaC <- function(A, D) {
    .Call(`_spca_atdaC`, A, D)
}

atdbC <- function(A, D, B) {
    .Call(`_spca_atdbC`, A, D, B)
}

avC <- function(A, v) {
    .Call(`_spca_avC`, A, v)
}

atvC <- function(A, v) {
    .Call(`_spca_atvC`, A, v)
}

vtaC <- function(v, A) {
    .Call(`_spca_vtaC`, v, A)
}

vtauC <- function(v, A, u) {
    .Call(`_spca_vtauC`, v, A, u)
}

vtvC <- function(v) {
    .Call(`_spca_vtvC`, v)
}

vtuC <- function(v, u) {
    .Call(`_spca_vtuC`, v, u)
}

traceC <- function(S) {
    .Call(`_spca_traceC`, S)
}

EigenC <- function(S) {
    .Call(`_spca_EigenC`, S)
}

compute_eigenvaluesC <- function(S) {
    .Call(`_spca_compute_eigenvaluesC`, S)
}

GenEigenC <- function(A, B) {
    .Call(`_spca_GenEigenC`, A, B)
}

solveC <- function(S) {
    .Call(`_spca_solveC`, S)
}

scaleC <- function(A, center = TRUE, scale = TRUE) {
    .Call(`_spca_scaleC`, A, center, scale)
}

scaleColsC <- function(A, normtype, sig) {
    .Call(`_spca_scaleColsC`, A, normtype, sig)
}

make_vexpSC <- function(A, S) {
    .Call(`_spca_make_vexpSC`, A, S)
}

var2corC <- function(S) {
    .Call(`_spca_var2corC`, S)
}

makeCorCompC <- function(A, S, d = 0L) {
    .Call(`_spca_makeCorCompC`, A, S, d)
}

makeCorScoresC <- function(T, d = 0L) {
    .Call(`_spca_makeCorScoresC`, T, d)
}

lsspcaTC <- function(X, ncomps = 0L, stop_criterion = 0L, exact_cvexp = FALSE, alpha = 0.95, ncompbycvexp = 0.95, method = as.character( c("c")), indvec_in = NULL, cardvec_in = NULL, PMPC = FALSE, PMS = FALSE, epsPMPC = 1E-5, epsPMS = 1E-7, maxiterPMPC = 300L, maxiterPMS = 200L, rank_tol = 0.0) {
    .Call(`_spca_lsspcaTC`, X, ncomps, stop_criterion, exact_cvexp, alpha, ncompbycvexp, method, indvec_in, cardvec_in, PMPC, PMS, epsPMPC, epsPMS, maxiterPMPC, maxiterPMS, rank_tol)
}

lsspcaC <- function(S, ncomps = 0L, selection_method = 0L, stop_criterion = 0L, exact_cvexp = FALSE, alpha = 0.95, ncompbycvexp = 0.95, method = as.character( c("c")), indvec_in = NULL, cardvec_in = NULL, PMPC = FALSE, PMS = FALSE, epsPMPC = 1E-5, epsPMS = 1E-7, maxiterPMPC = 100L, maxiterPMS = 200L, rank_tol = 0.0) {
    .Call(`_spca_lsspcaC`, S, ncomps, selection_method, stop_criterion, exact_cvexp, alpha, ncompbycvexp, method, indvec_in, cardvec_in, PMPC, PMS, epsPMPC, epsPMS, maxiterPMPC, maxiterPMS, rank_tol)
}

